name: SonarQube Scan

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - run: pip install bandit semgrep pip-audit

      - name: Bandit Scan
        run: bandit -r Chinna/vulndemo  || true

      - name: Semgrep Scan
        run: semgrep --config=p/owasp-top-ten Chinna/vulndemo

      - name: Dependency Audit
        run: pip-audit -r Chinna/vulndemo     

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v6
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        with:
          projectBaseDir: Chinna/vulndemo
